import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "./members/navbar/TopNav";


export const metadata: Metadata = {
  title: "NextDataMG1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav />
          <main className='container mx-auto p-10'>
          {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
